### PR TITLE
Update examples to use `us-west-2`

### PR DESCRIPTION
**Pull request by gjoseph92**
Now that Coiled supports `us-west-2`, we can use that!

This also adds a script to build software environments in parallel in multiple regions. By creating envs in multiple regions up front, the first person won't have to wait for an image build when they spin up a cluster in one of the demos.

Also added `jupyterlab-system-monitor` for fun.

cc @scottyhq

### CODE REVIEW

**Comment by scottyhq** [comment]
fantastic! @gjoseph92 thoughts on a 0.2.1 release? I think otherwise if people are new to stackstac and following on read-the-docs the cluster config still shows `us-west-1`.

**Comment by gjoseph92** [comment]
Or I could switch readthedocs from `stable` to `latest` 🤔  (don't love that but also nothing in the actual code has changed since 0.2.1, so making a release feels kinda silly.)
Or I could bump the 0.2.0 tag ahead a commit?

https://stackstac.readthedocs.io/en/latest/examples/cluster.html

**Comment by scottyhq** [comment]
> Or I could switch readthedocs from stable to latest 

also works! if i go to https://stackstac.readthedocs.io for some reason the lower right pull-down menu to change versions doesn't work for me on safari... does on chrome though. seems like just switching the default to 'latest' is an easy temporary fix, can always move back to 'stable' after the next release.

**Comment by gjoseph92** [comment]
Just switched it. http://stackstac.readthedocs.io is directing me to `latest` now.

**Pull request merged**
